### PR TITLE
Linearizable agenda

### PR DESCRIPTION
**Pull request by delapuente**
@dontcallmedom can you give it a shallow review so we can merge it and give the opportunity to the committee to review its live version? (I'm disabling the access from the front page).

### CODE REVIEW

**Comment by delapuente** [comment]
I just realize I can serve the in-progress version using RawGit. I'll send an email.

**Comment by delapuente** [comment]
@dontcallmedom, can you review the agenda and wording? @developdata and I think the agenda is stable enough although it may vary during these weeks.

**Review by dontcallmedom — COMMENTED** [review]
Looks very good overall; my only remark is that I think we should start the first day with a status review of WebVR, both from a technology and implementation perspective. This means moving or removing one of the existing plenary sessions -  I think which one will be clearer once we start assigning people to lead the discussions

**Comment by delapuente** [comment]
Agree, actually @developdata and I are waiting after assigning people to the sessions to make some other improvements. Can we merge this version?

**Pull request merged**
